version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/adaptive_learning
      - REDIS_URL=redis://redis:6379/0
      - VECTOR_DB_URL=http://vector_db:6333
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app:/app/app
    depends_on:
      - db
      - redis
      - vector_db
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/adaptive_learning
      - REDIS_URL=redis://redis:6379/0
      - VECTOR_DB_URL=http://vector_db:6333
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app:/app/app
    depends_on:
      - db
      - redis
      - api
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adaptive_learning
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  vector_db:
    image: pinecone/pinecone:latest
    ports:
      - "6333:6333"
    volumes:
      - pinecone_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pinecone_data:
