FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода приложения
COPY . /app/

# Переменные окружения
ENV PYTHONPATH=/app

# Команда для запуска worker
CMD celery -A app.tasks worker --loglevel=info
